GET http://localhost:3000/api/libros HTTP/1.1

###

POST http://localhost:3000/api/libros
Content-Type: application/json

{
    "dates": {
        "titulo": "libro falso",
        "descripcion": "Como todo en la vida esto no es mas que una simple ilusion",
        "clasificacion": "Todos",
        "num_paginas": 111,
        "precio": 2000,
        "stock": 1,
        "es_fisico": 0, 
        "año_publicacion": 2001,
        "id_editorial": 1,
        "id_autor": 1
    }
}

###

DELETE http://localhost:3000/api/libros/10 HTTP/1.1

###

PUT http://localhost:3000/api/libros/10 HTTP/1.1
Content-Type: application/json

{
    "dates": {
        "titulo": "libro real",
        "descripcion": "mas real que las mujeres",
        "clasificacion": "+18",
        "num_paginas": 1,
        "precio": 3000,
        "stock": 21,
        "es_fisico": 1, 
        "año_publicacion": "2002",
        "id_editorial": 1,
        "id_autor": 1
    }
}

###

GET http://localhost:3000/api/libros/ordenar/titulo HTTP/1.1

###

GET http://localhost:3000/api/usuarios HTTP/1.1

###
POST http://localhost:3000/usuario/login
Content-Type: application/json

{   
    "user": {
        "key": "juan hot",
        "clave": "contra1234"
    }
}

###

POST http://localhost:3000/usuario/register
Content-Type: application/json

{ 
    "user": {
        "email": "juanhot@hotmail.com",
        "telefono": "1122334455",
        "clave": "contra1234",
        "nombre": "Cottier",
        "apellido": "Juan",
        "direccion": "casa 123",
        "fecha_nacimiento": "2024-11-01",
        "alias": "juan hot"    
    }
}

###

POST http://localhost:3000/guardar/libro 
Content-Type: application/json

{
    "save": {
        "id_libro": 1,
        "id_usuario": 1
    }
}

###

POST http://localhost:3000/guardar/categoria
Content-Type: application/json

{
    "save": {
        "id_categoria": 3,
        "id_usuario": 1
    }
}

###

POST http://localhost:3000/guardar/autor
Content-Type: application/json

{
    "save": {
        "id_autor": 2,
        "id_usuario": 1
    }
}

###

GET http://localhost:3000/api/libros/desc HTTP/1.1

###

GET http://localhost:3000/carrito/items/ver/1 HTTP/1.1

###

POST http://localhost:3000/carrito/insertar HTTP/1.1
Content-Type: application/json

{
    "cart": {
        "id_libro": 1,
        "id_usuario": 1
    }
}

###

POST http://localhost:3000/carrito/pedir HTTP/1.1
Content-Type: application/json

{
    "order": {
        "total": 12345,
        "fecha_estimada": "2001-1-1",
        "id_usuario": 2
    }
}

###

GET http://localhost:3000/libro/ver HTTP/1.1


###
GET http://localhost:3000/libro/ver/1 HTTP/1.1

###
GET http://localhost:3000/api/libro/id_libro?orden=desc HTTP/1.1

###

GET http://localhost:3000/libro/filtrar?categoria=utopia&autor=Martin Kohan HTTP/1.1

###

GET http://localhost:3000/libro/buscar/fa HTTP/1.1

###

GET http://localhost:3000/api/libros/id/1 HTTP/1.1